name: LatinOcean
favicon: null
layout_spectrum: 0.9793832395225763
typography_spectrum: 0.1622804207727313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdce1'
    - '#eca800'
    - '#121f23'
    - '#72675c'
    - '#988d83'
  brandStrength: 0.625
  lightness: 0.5948573825880885
  saturation: 0.8265243545174599
  rhythmicContrast: 0.2174809833522886
purpose: []
